#!/bin/bash
crs_11_brute_force.sh off
crs_11_dos_protection.sh off
crs_11_proxy_abuse.sh off
crs_11_slow_dos_protection.sh off
crs_16_scanner_integration.sh off
crs_20_protocol_violations.sh off
crs_21_protocol_anomalies.sh off
crs_23_request_limits.sh off
crs_25_cc_track_pan.sh off
crs_30_http_policy.sh off
crs_35_bad_robots.sh off
crs_40_appsensor_detection_point_2.0_setup.sh off
crs_40_appsensor_detection_point_2.1_request_exception.sh off
crs_40_appsensor_detection_point_2.9_honeytrap.sh off
crs_40_appsensor_detection_point_3.0_end.sh off
crs_40_generic_attacks.sh off
crs_40_http_parameter_pollution.sh off
crs_41_sql_injection_attacks.sh off
crs_41_xss_attacks.sh off
crs_42_csp_enforcement.sh off
crs_42_tight_security.sh off
crs_45_trojans.sh off
crs_46_scanner_integration.sh off
crs_47_common_exceptions.sh off
crs_48_bayes_analysis.sh off
crs_49_inbound_blocking.sh off
crs_50_outbound.sh off
crs_55_response_profiling.sh off
crs_56_pvi_checks.sh off
crs_59_outbound_blocking.sh off
crs_60_correlation.sh off
crs_61_ip_forensics.sh off

