./crs_11_brute_force.sh on
./crs_11_dos_protection.sh on
./crs_11_proxy_abuse.sh on
./crs_11_slow_dos_protection.sh on
./crs_16_scanner_integration.sh on
./crs_20_protocol_violations.sh on
./crs_21_protocol_anomalies.sh on
./crs_23_request_limits.sh on
./crs_25_cc_track_pan.sh on
./crs_30_http_policy.sh on
./crs_35_bad_robots.sh on
./crs_40_appsensor_detection_point_2.0_setup.sh on
./crs_40_appsensor_detection_point_2.1_request_exception.sh on
./crs_40_appsensor_detection_point_2.9_honeytrap.sh on
./crs_40_appsensor_detection_point_3.0_end.sh on
./crs_40_generic_attacks.sh on
./crs_40_http_parameter_pollution.sh on
./crs_41_sql_injection_attacks.sh on
./crs_41_xss_attacks.sh on
./crs_42_csp_enforcement.sh on
./crs_42_tight_security.sh on
./crs_45_trojans.sh on
./crs_46_scanner_integration.sh on
./crs_47_common_exceptions.sh on
./crs_48_bayes_analysis.sh on
./crs_49_inbound_blocking.sh on
./crs_50_outbound.sh on
./crs_55_response_profiling.sh on
./crs_56_pvi_checks.sh on
./crs_59_outbound_blocking.sh on
./crs_60_correlation.sh on
./crs_61_ip_forensics.sh on

